### ISSUE TITLE
Pseudo elements `::-webkit-outer-spin-button` and `::-webkit-inner-spin-button` being removed

### ISSUE THREAD

**Issue by jacobbuck** [giakki/uncss#206] opened 2016-01-13 20:42 UTC

**Comment by XhmikosR** [comment] 2016-02-14 08:32
@mikelambert: I think this was fixed by your patch in https://github.com/giakki/uncss/pull/211, right?

**Comment by XhmikosR** [comment] 2016-02-14 08:34
BTW this is duplicate of #199

**Closed by XhmikosR** 2016-02-14 08:34 UTC
Labels: bug, duplicate

**Comment by mikelambert** [comment] 2016-02-14 08:38
Yes, my commit should have fixed this.

**Comment by jacobbuck** [comment] 2016-02-14 10:33
:+1:
