### ISSUE TITLE
Have no proxy setting if type is Url

### ISSUE THREAD

**Issue by bcguan2008** [giakki/uncss#177] opened 2015-07-09 03:21 UTC
i have no idea if i need to change proxy. that's my code

```
.pipe(uncss({
                    html: ['http://www.google.com/'],
                }))
```

but my default proxy can not access google.

so i want add proxy seeting , but uncss does not provide options. 

I add proxy info in file gulp-uncss\node_modules\uncss\src\phantom.js line 29,   then works fine.

https://github.com/giakki/uncss/blob/master/src/phantom.js#L30
would you please advise ?
```
function init(instance) {
    if (instance) {
        phantom = instance;
        return null;
    }
    return new promise(function (resolve) {
        resolve(phridge.spawn({
            //add proxy 
            //proxy:"http://XXXXX:XXX",
            ignoreSslErrors: 'yes',
            sslProtocol: 'any'
        }));
    }).then(function (ph) {
        phantom = ph;
    }).disposer(phridge.disposeAll);
}
```

**Comment by RyanZim** [comment] 2016-06-25 19:31
@mikelambert Dupe of #176 IMO.

**Closed** 2016-06-26 19:53 UTC
