### ISSUE TITLE
Fatal error: PhantomJS: Cannot open about:blank

### ISSUE THREAD

**Issue by johntrandall** [giakki/uncss#150] opened 2015-02-12 17:03 UTC
Hello. 

Thanks for building uncss. It's awesome. 

I'm using a WordPress with Gravity Forms, which uses a peculiar hack.... it makes ajax calls from within an iFrame, and the iFrame is pointed at _about:blank. Unfortunately, PhantomJS chokes on this link, causing uncss to quit with the error:

    Fatal error: PhantomJS: Cannot open about:blank

I think, but I'm not certain, that this is related to the way PhantomJS deals with SSL. I don't really know much about SSL or SSL errors, However, Google tells me that [CasperJS users have experienced the same issue](http://stackoverflow.com/questions/13819159/debug-aboutblank-in-casperjs), and the workaround was to tell PhantomJS to ignore SSL errors by running it with the flag __'--ignore-ssl-errors=true'__.

If this is, in-fact, related to the SSL problem, might a simple fix be to just have UnCSS run PhantomJS with this flag? I would think that SSL errors are not germane to what uncss does, so perhaps they can be ignored without repercussions. 

(If it isn't related to the SSL problem, any advice for me?)

**Comment by johntrandall** [comment] 2015-02-12 17:09
I just checked [the source, and it seems that Phantom is already set to ignore SSL errors](https://github.com/giakki/uncss/blob/master/src/phantom.js#L25). So, as long as that is working, I guess I'm barking up the wrong tree. :(

Any other suggestions?

**Comment by johntrandall** [comment] 2015-02-12 17:13
[line25 in phantom.js](https://github.com/giakki/uncss/blob/master/src/phantom.js#L25)

Should 

    // Convert to bluebird promise
    return new promise(function (resolve) {
        resolve(phridge.spawn({
            ignoreSslErrors: 'yes',
            sslProtocol: 'any'
        }));
    ....
be

    ignoreSslErrors: 'true',


Sorry for the speculation. I'm pretty green.

**Comment by ben-eb** [comment] 2015-02-12 17:31
Both are accepted: http://phantomjs.org/api/command-line.html

**Comment by ben-eb** [comment] 2015-02-13 17:21
@johntrandall You might want to look into setting up a http proxy for your site, which blocks the troublesome script, and then have UnCSS analyse the site via the proxy instead. I'm not sure what we can do in UnCSS that wouldn't be a hacky way of solving this.

https://github.com/nodejitsu/node-http-proxy

**Comment by johntrandall** [comment] 2015-02-13 20:31
Thanks @ben-eb. I'll try that.

**Comment by ifaris7** [comment] 2015-02-23 11:29
+1 i have the same problem

**Comment by candidosales** [comment] 2015-03-04 03:37
+1

**Comment by ben-eb** [comment] 2015-03-08 00:44
I think the original report threw me off somewhat; I noticed a regression in https://github.com/cssstats/cssstats when I tried to upgrade gulp-uncss to `1.0.0`:

```
/Users/bbriggs/projects/cssstats/node_modules/gulp-uncss/node_modules/uncss/node_modules/bluebird/js/main/async.js:36
        fn = function () { throw arg; };
                                 ^
Error: PhantomJS: Cannot open about:blank
    at reject (/Users/bbriggs/projects/cssstats/node_modules/gulp-uncss/node_modules/uncss/node_modules/phridge/lib/phantom/start.js:71)
    at :4
    at :/modules/webpage.js:281
    -----------------------------------------------------------------------
    at Phantom._send (/Users/bbriggs/projects/cssstats/node_modules/gulp-uncss/node_modules/uncss/node_modules/phridge/lib/Phantom.js:165:20)
    at Page.run (/Users/bbriggs/projects/cssstats/node_modules/gulp-uncss/node_modules/uncss/node_modules/phridge/lib/Page.js:62:25)
    at /Users/bbriggs/projects/cssstats/node_modules/gulp-uncss/node_modules/uncss/src/phantom.js:125:21
    at tryCatchReject (/Users/bbriggs/projects/cssstats/node_modules/gulp-uncss/node_modules/uncss/node_modules/phridge/node_modules/when/lib/makePromise.js:845:30)
    at runContinuation1 (/Users/bbriggs/projects/cssstats/node_modules/gulp-uncss/node_modules/uncss/node_modules/phridge/node_modules/when/lib/makePromise.js:804:4)
    at Fulfilled.when (/Users/bbriggs/projects/cssstats/node_modules/gulp-uncss/node_modules/uncss/node_modules/phridge/node_modules/when/lib/makePromise.js:592:4)
    at Pending.run (/Users/bbriggs/projects/cssstats/node_modules/gulp-uncss/node_modules/uncss/node_modules/phridge/node_modules/when/lib/makePromise.js:483:13)
    at Scheduler._drain (/Users/bbriggs/projects/cssstats/node_modules/gulp-uncss/node_modules/uncss/node_modules/phridge/node_modules/when/lib/Scheduler.js:62:19)
    at Scheduler.drain (/Users/bbriggs/projects/cssstats/node_modules/gulp-uncss/node_modules/uncss/node_modules/phridge/node_modules/when/lib/Scheduler.js:27:9)
    at process._tickCallback (node.js:419:13)
```

In this instance the build process is running UnCSS on handlebars partials, which seems to be fine when using the old version of UnCSS, but fails on newer versions.

**Comment by piotrd** [comment] 2015-03-08 01:34
I think I'm facing the same problem - I am passing a tree of local directories containing HTML files to UnCSS:

```
/usr/local/lib/node_modules/uncss/node_modules/bluebird/js/main/async.js:36
        fn = function () { throw arg; };
                                 ^
Error: PhantomJS: Cannot open about:blank
    at reject (/usr/local/lib/node_modules/uncss/node_modules/phridge/lib/phantom/start.js:71)
    at :4
    at :/modules/webpage.js:281
    -----------------------------------------------------------------------
    at Phantom._send (/usr/local/lib/node_modules/uncss/node_modules/phridge/lib/Phantom.js:165:20)
    at Page.run (/usr/local/lib/node_modules/uncss/node_modules/phridge/lib/Page.js:62:25)
    at /usr/local/lib/node_modules/uncss/src/phantom.js:125:21
    at tryCatchReject (/usr/local/lib/node_modules/uncss/node_modules/phridge/node_modules/when/lib/makePromise.js:845:30)
    at runContinuation1 (/usr/local/lib/node_modules/uncss/node_modules/phridge/node_modules/when/lib/makePromise.js:804:4)
    at Fulfilled.when (/usr/local/lib/node_modules/uncss/node_modules/phridge/node_modules/when/lib/makePromise.js:592:4)
    at Pending.run (/usr/local/lib/node_modules/uncss/node_modules/phridge/node_modules/when/lib/makePromise.js:483:13)
    at Scheduler._drain (/usr/local/lib/node_modules/uncss/node_modules/phridge/node_modules/when/lib/Scheduler.js:62:19)
    at Scheduler.drain (/usr/local/lib/node_modules/uncss/node_modules/phridge/node_modules/when/lib/Scheduler.js:27:9)
    at process._tickCallback (node.js:442:13)
```

**Comment by overclokk** [comment] 2015-03-08 15:15
+1 I have the same problem

**Comment by giakki** [comment] 2015-03-08 18:06
Thanks everyone for the reports. I am looking into it!

**Comment by elamperti** [comment] 2015-03-15 16:37
Temporary workaround: version 0.10.0 works correctly for me.

**Comment by leetomblin** [comment] 2015-03-22 00:40
Couldn't seem to get 0.10.0 working with grunt.

Any other fix for this?

**Comment by In4matik** [comment] 2015-03-22 23:46
Looking for a fix too... Any updates?

**Comment by Metrakit** [comment] 2015-03-30 12:58
I have the same problem when I'm using symfony 2 with the twig template on a Vagrant

**Comment by arielespinoza** [comment] 2015-04-16 18:26
Where can get the version 0.10.0 ??

**Comment by piotrd** [comment] 2015-04-16 19:31
@arielespinoza: o_O 

![image](https://cloud.githubusercontent.com/assets/176665/7189554/fa996c28-e47f-11e4-8306-708a2c6655a8.png)

**Comment by arielespinoza** [comment] 2015-04-16 19:41
@giakki  Thanks!

.php files can be used? or just be .html files?

For example:

uncss: {
        dist: {
            files: [
                { src: 'dist/index.php', dest: 'dist/css/tidy.css' }
            ]
        }
    }

**Comment by AlexDubstone** [comment] 2015-05-13 15:43
Same here, unfortunately. Works with html files but as soon as I switch to a php file I get `phantomJS: can not open about: blank`

**Comment by PixelbarEupen** [comment] 2015-05-20 14:23
Got the same problem. Could not find any fix

**Comment by yumyo** [comment] 2015-05-20 14:25
same here : (

**Comment by monte-hayward** [comment] 2015-05-23 00:48
Same is true for markdown .md files.
```
Verifying property uncss.dist exists in config...OK
Files: 404.md, README.md, about.md, contact.md, index.md, pci-preflight.md, privacy.md, services.md -> assets/css/main.min.css
Options: report=false, ignore=["iframe","about:blank"], ignoreSheets=[{}], timeout=1000, htmlroot="public"
Fatal error: PhantomJS: Cannot open about:blank
``

**Comment by pascalhofmann** [comment] 2015-05-28 14:40
Got the same problem. :(

**Comment by envomer** [comment] 2015-06-12 19:36
Same issue here as well. any bugfix yet??

**Comment by garethtalty** [comment] 2015-07-06 10:08
+1

**Comment by inkcreativ** [comment] 2015-08-16 09:42
Please is there anyone here who have the answer?

txs

**Comment by adamkarb** [comment] 2015-09-03 02:41
This is devilish

**Comment by elamperti** [comment] 2015-09-20 21:22
This problem was introduced on commit 9b032eeb where the function fromLocal() was changed in `src/phantom.js`. Turning it back to its original form solves this issue, though that would disable the feature introduced in the broken commit (reporting errors' filenames).

I think the problem is around [lines 131~140](https://github.com/giakki/uncss/blob/4f915eb785afaffb3e26d25df5d9e733fb68ea13/src/phantom.js#L131-L140) of the current version of `src/phantom.js`, probably (but I'm not entirely sure) because it is trying to open a local path as a URL (which would be an invalid URL) and thus failing to fetch it.

**Comment by anthonyfio** [comment] 2015-10-23 22:40
+1 same problem with command line interface

**Comment by AndrewLosev** [comment] 2015-11-22 21:30
I have the same problem :( "Error: PhantomJS: Cannot open about:blank"
It works with HTML and doesn't with PHP.
I hope somebody could help))

**Comment by mikegyi** [comment] 2015-11-25 18:01
+1 

Had to temporarily change from .php to .html - wasn't too much fuss!

**Comment by chucklima** [comment] 2016-01-19 21:16
Same problem here.

I had bad characters is directory names - trademark, registered, single ticks.

**Comment by markau** [comment] 2016-01-22 01:21
@elamperti Thank you, your patch got .cshtml files working for me.

**Comment by HugoHeneault** [comment] 2016-01-22 15:51
I can't believe this bug it still there... :sob: 

Uncss is so awesome I'm having a hard time not using it...

**Comment by Rodrigo54** [comment] 2016-01-22 19:33
@elamperti Thank you, I managed to use all my .php files with the changes of your pull request #192

**Closed** 2016-01-28 10:18 UTC

**Comment by HugoHeneault** [comment] 2016-01-28 10:41
Awesome!

**Comment by opoani** [comment] 2016-02-04 13:42
Anyone managed it to work with .cshtml files ? I constantly get:
Fatal error: PhantomJS: Cannot open about:blank

**Comment by elamperti** [comment] 2016-02-04 13:44
@opoani which version of uncss are you using? This should be fixed in 0.13.0

**Comment by opoani** [comment] 2016-02-04 13:52
Im using 0.13.0 as far as i can tell

**Comment by opoani** [comment] 2016-02-04 13:57
Im using it together with grunt-uncss ,
        uncss: {
  dist: {
    files: [
      {
        src: './Views/**/*.cshtml',
        dest: './Stylesheets/tidy/tidy.css',
            options: {
                      report: 'min' 
                  }
      }
    ]
  }
}

**Comment by markau** [comment] 2016-02-04 22:05
Whilst the 0.13.0 update did fix the phantomJS error for .cshtml files (for gulp-uncss at least), the result was a lot of missing css from my bundled output. I expect this is due to the fact that .cshtml are html templates and not rendered html output; with the added complication of _Layout.cshtml (i.e. master templates). PhantomJS may have trouble parsing the tempates to find the pertinent CSS. I did not have time to investigate further. FYI @opoani.

**Comment by dr-martin** [comment] 2016-09-06 22:49
@opoani Updating to 0.13.0 fix my problem, thanks!
