### ISSUE TITLE
How to use it for removing unused inline CSS

### ISSUE THREAD

**Issue by biggenius** [giakki/uncss#243] opened 2016-06-20 18:24 UTC
Any workaround?

**Comment by RyanZim** [comment] 2016-06-21 00:20
Duplicate of #69. Feel free to contribute a PR.

As far as a workaround, you could copy your inline CSS to a separate file and use the commandline `-s` option. https://github.com/giakki/uncss#from-the-command-line Take the output and paste it back into the html file.

CC: @mikelambert

**Closed** 2016-06-21 01:08 UTC
