### ISSUE TITLE
all classes and ids getting stripped off

### ISSUE THREAD

**Issue by binarytrance** [giakki/uncss#277] opened 2016-12-23 08:19 UTC
I just started using uncss and i tried it on one of my pages. I found out that in the output css file, all the classes and ids are getting removed. the output file contains just the font-face properties and a couple of `@media` statements which only have comments inside them. I have my working directory uploaded in this [repo](https://github.com/binarytrance/uncss_test). It contains all the css including the uncssed version in the directory named `dist`. Please take a look and suggest solutions.

I will like to point out that I tried uncss with other html/css files and it works great. Its facing problems only with those particular files (the ones in the repo). It might be a parsing issue or something else, hopefully i'll find an answer soon.

**Comment by RyanZim** [comment] 2016-12-24 01:48
@binarytrance This is pretty well a dupe of https://github.com/giakki/uncss/issues/257.

Loading typekit (`<script src="https://use.typekit.net/svf8acc.js"></script>`) either takes too long, or PhantomJS can't load it. It then gives up and processes your page as if it contained only the html up until your script tag. That html doesn't contain any of your content, unfortunately.

In short, uncss just doesn't play well with slow scripts in the head, especially typekit.

**Closed** 2016-12-24 06:09 UTC
