### ISSUE TITLE
Change user agent in header for mobile version of website

### ISSUE THREAD

**Issue by Ajeetlakhani** [giakki/uncss#222] opened 2016-03-21 15:05 UTC
For `http://example.com` different html and js is rendered for mobile and desktop version. So is it possible to change page user agent as we do in phantomJS?

**Comment by RyanZim** [comment] 2016-05-27 19:23
Don't know. @mikelambert?

**Comment by mikelambert** [comment] 2016-05-27 20:23
No such feature/option right now...if PhantomJS supports it, then I assume it's just a matter of making an option that plumbs it all the way down to our use of the PhantomJS API.

**Comment by RyanZim** [comment] 2016-05-27 20:26
Oops, dupe of #176. Please close @mikelambert.

**Closed** 2016-05-27 20:28 UTC
