### ISSUE TITLE
Possible to return the CSS that is being cut out?

### ISSUE THREAD

**Issue by corysimmons** [giakki/uncss#173] opened 2015-05-14 19:26 UTC
UnCSS seems to just return the value of the post-uncss CSS. Is there a way to see what it's cutting out aside from doing a diff after the fact?

**Comment by corysimmons** [comment] 2015-05-14 19:27
Use case: manually removing CSS blocks that I'm not using on a project.

**Comment by ben-eb** [comment] 2015-05-14 19:49
This is a duplicate of https://github.com/giakki/uncss/issues/49.

**Closed** 2015-05-14 20:00 UTC
