### ISSUE TITLE
how to deal with 'ReferenceError: Can't find variable: $' error

### ISSUE THREAD

**Issue by lorvent** [giakki/uncss#232] opened 2016-05-13 01:43 UTC
It was working fine for some files but now all of sudden, getting this error

`ReferenceError: Can't find variable: $`

how to fix it?

atleast if i know, on which file i am getting this error...i will be able to fix it.

thanks.

**Comment by RyanZim** [comment] 2016-05-24 15:40
I'm guessing you forgot to include jQuery in one of your html files. You could try opening each page in the browser and looking at the console.

**Comment by lorvent** [comment] 2016-05-24 15:52
I don't think so because everypage uses many jquery plugins including bootstrap so that should not be the issue

but can you help me finding out more information?

like using plumber to get file name etc...

**Comment by RyanZim** [comment] 2016-05-24 16:10
Not sure. Perhaps @XhmikosR or @mikelambert could help you better.

**Comment by XhmikosR** [comment] 2016-05-24 17:47
Unfortunately, this is an issue that happens for so long and personally I can't figure out why.

The solution is to either use an older uncss version (0.12.1 doesn't throw those errors), or stop inlining JS code.

**Comment by mikelambert** [comment] 2016-05-24 18:16
I'll say the same thing I said in https://github.com/giakki/uncss/issues/220, if you want to give a relatively small reproducible test case, it's possible someone can look into it.

My guess as to the reason 0.12.1 doesn't throw these errors (this is for you too @XhmikosR) is that 0.21 just silently drops the warnings. This particular change was only included in 0.13: https://github.com/giakki/uncss/commit/62145b351fa9eedccdd8eeb5b8d5f14db72e4100

So you can downgrade, but I suspect you're really just hiding existing errors by doing so.

**Comment by lorvent** [comment] 2016-05-24 18:44
hmm nice tip but that doesn't serve real purpose as its just hiding errors,

whereas my whole idea of using build systems is to improve code quality...

**Comment by XhmikosR** [comment] 2016-05-24 19:03
Well in my case moving all JS to external files fixed the errors.

Plus all the advantages of doing so.

Ideally the issue should be fixed but I've yet to make a small test case.

I'll try to do it later or tomorrow.

**Comment by jogaco** [comment] 2016-07-30 16:05
Found the same issue.
This minimal example reproduces the error.

```
<!DOCTYPE html>
<html>
  <head>
    <script src="https://code.jquery.com/jquery-2.2.4.min.js" async="async"></script>
    <link rel="stylesheet" media="all" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />

    <script>
      function a() {
        $('#div').show();
      }
      a();
    </script>
  </head>
  <body>
  </body>
</html>
```

**Comment by RyanZim** [comment] 2016-07-30 17:57
**Confirmed.**

I'm getting ready to do a git bisect to find this bug.

@jogaco Thanks for posting!

**Comment by lorvent** [comment] 2016-07-30 18:20
in mycase, if you add js in html page we will get this problem,
move it to seperate js file

**Comment by RyanZim** [comment] 2016-07-30 18:23
@lorvent Yes, moving JS to a separate file fixes it, but uncss should support inline JS.

I'm currently running `git bisect` to find which commit is responsible for this error.

**Comment by RyanZim** [comment] 2016-07-30 18:26
**And the results are:**
```
62145b351fa9eedccdd8eeb5b8d5f14db72e4100 is the first bad commit
commit 62145b351fa9eedccdd8eeb5b8d5f14db72e4100
Author: Giacomo Martino <martino.giacomo@gmail.com>
Date:   Sun Mar 8 17:09:16 2015 +0100

    Output phantom.js errors to `stderr`.
    Use .contain

:040000 040000 812459bd91a7e73965bcadc7f0519a4c7fb21716 0e4e481eabfb8712f441e5ee469d0ed14ee88446 M	src
:040000 040000 21939bef4d3e7e6692b4725739e13591dc236480 88ee814adbd3125c385c4ec39232e8e18bedeea5 M	tests
```
@mikelambert You were right:
> My guess as to the reason 0.12.1 doesn't throw these errors (this is for you too @XhmikosR) is that 0.21 just silently drops the warnings. This particular change was only included in 0.13: 62145b3

The first bad commit is 62145b351fa9eedccdd8eeb5b8d5f14db72e4100.

**Comment by RyanZim** [comment] 2016-07-30 18:32
@XhmikosR Is this a PhantomJS bug? Perhaps https://github.com/ariya/phantomjs/issues/14422 or https://github.com/ariya/phantomjs/issues/14316?

**Comment by mikelambert** [comment] 2016-07-30 20:26
The above HTML file uses an async sync, meaning the calling page will not block to wait for that script to load before loading/running the rest of the page. So when the call to `$('#div')` occurs, there is no guarantee that the jquery code has been loaded yet. And if the jquery code has not been loaded, I would expect you to get an error very similar to `Can't find variable: $`.

So from my perspective, the above HTML file is broken code, and uncss/phantom is just errorring on the broken code.

**Comment by XhmikosR** [comment] 2016-07-30 20:58
That is correct.

my example in #220 has a snippet which doesn't use async that triggers the
error though.

**Comment by mikelambert** [comment] 2016-07-31 00:27
Well the minimal repro example above has a bug, which uncss found. Your example in #220 is probably due to a different issue then (though due to the same issue of a jquery file not being loaded properly). I'll try to respond with some ideas in that thread.

**Comment by jogaco** [comment] 2016-07-31 14:22
What about this?

```
<!DOCTYPE html>
<html>
  <head>
    <script src="https://code.jquery.com/jquery-2.2.4.min.js" async="async"></script>
    <link rel="stylesheet" media="all" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
    <script>
   $(document).ready(function(){
      function a() {
        $('#div').show();
      }
      a();
    });
    </script>
  </head>
  <body>
  </body>
</html>

```

**Comment by XhmikosR** [comment] 2016-07-31 15:31
You are still missing the point. You are using async.

**Comment by mikelambert** [comment] 2016-07-31 20:40
You are still referencing the $ variable before jQuery is loaded, so you will still get that error. You can either write code that doesn't use $ until after the page is loaded (which your example tried but did not do), or you can stop using async (and ideally move your <script> tags out of your <head>)

**Comment by jogaco** [comment] 2016-08-01 11:40
Got it!

**Comment by RyanZim** [comment] 2016-08-01 15:06
Oops, didn't look at the test case close enough.

**Comment by RyanZim** [comment] 2017-08-07 22:35
Can anyone check if this is fixed with uncss 0.15.0? We switched to jsdom in this release.

**Comment by XhmikosR** [comment] 2017-08-07 22:40
Doesn't seem to throw even with `async` for the above sample https://github.com/giakki/uncss/issues/232#issuecomment-236432586.

But the test case from https://github.com/giakki/uncss/issues/220#issuecomment-223927766 still throws because there the file is local.

I even tried with `--htmlroot` in the cli and still can't find the local jquery file.

**Comment by XhmikosR** [comment] 2017-08-07 22:41
Err scratch that. It works fine. I need to sleep :/

**Closed by XhmikosR** 2017-08-07 22:41 UTC

**Comment by XhmikosR** [comment] 2017-08-07 22:43
Although, it still misses the JavaScript added selectors. This is still an issue, right?

**Comment by mikelambert** [comment] 2017-08-07 22:52
I'm not sure what you mean by 'js added selectors'. I don't see that mentioned in this issue?

If you're talking about classes that get added to the page at runtime in response to user events, then yes, it misses those. I consider this a "Will Not Fix" bug though.

**Comment by XhmikosR** [comment] 2017-08-08 06:44
Why is that? It's a pretty common use case and almost every single website does this.

On a side note if you try my example from https://github.com/giakki/uncss/issues/220#issuecomment-223927766 with the latest version, it even misses the inline styles.

**Comment by XhmikosR** [comment] 2017-08-08 06:45
```html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>uncss TypeError demo</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/4.1.1/normalize.min.css">
    <style>
        .content {
            margin: 20px;
        }

        .red {
            color: red;
        }

        .green {
            color: green;
        }
    </style>
</head>

<body>
    <div class="content">
        <span class="green">This text should be green and change to red after page load.</span>
    </div>
    <script src="jquery.slim.min.js"></script>
    <script>
        $(function() {
            $(".green").removeClass("green").addClass("red");
        });
    </script>
</body>
</html>
```

output css

```css
/*** uncss> filename: https://cdnjs.cloudflare.com/ajax/libs/normalize/4.1.1/normalize.min.css ***/html{font-family:sans-serif;-ms-text-size-adjust:100%;-webkit-text-size-adjust:100%}body{margin:0}::-webkit-input-placeholder{color:inherit;opacity:.54}::-webkit-file-upload-button{-webkit-appearance:button;font:inherit}/*# sourceMappingURL=normalize.min.css.map */

```

`.content` isn't there at all.

**Comment by mikelambert** [comment] 2017-08-08 07:28
Sigh. These are probably best discussed on another bug. I am not clear why you're trying to discuss a hodgepodge of random complaints in this bug, since AFAICT this bug has nothing to do with these two issues you just brought up?

Can you please file individual requests, one for each independent issue, to help keep this project clean and coherent?

I will be happy to respond to your complaints (to explain why they are impossible and/or detrimental to your own stated end goals) in any individual bugs you file, since it does not make sense to do this here, as that will only continue to spam the others in this thread who do not care about your personal bugs.

Thanks

**Comment by LuisAlejandro** [comment] 2020-02-22 04:36
For everyone still having this error, this could be happening to you: https://github.com/uncss/uncss/issues/268#issuecomment-589917479

**Comment by cresolindiateam** [comment] 2021-01-19 12:28
attach files by dragging & dropping
