### ISSUE TITLE
Create a File or Output of the Unused Css (stripped out code)

### ISSUE THREAD

**Issue by rooksstrife** [giakki/uncss#210] opened 2016-01-27 22:50 UTC
It would be awesome to return a file with the stripped out code or output it somehow somewhere.  That would be way easier to see what got hacked out and comb through that to add to the ignore!

Example:
File: unused.css
.not{color:#000}.another{display:block} etc...

**Comment by ben-eb** [comment] 2016-01-28 00:23
Duplicate of https://github.com/giakki/uncss/issues/49.

**Comment by RyanZim** [comment] 2016-05-27 19:27
@mikelambert Can you close this as per @ben-eb?

**Closed** 2016-05-27 20:23 UTC
