### ISSUE TITLE
Doesn't look at style tags

### ISSUE THREAD

**Issue by Synchro** [giakki/uncss#208] opened 2016-01-15 16:26 UTC
I'm trying to use uncss on a self-contained file where all css is in style tags. When I run uncss on it, it crashes out saying `Error: UnCSS: no stylesheets found`. In this particular file I have 12,000 lines of CSS (so you see why I'm doing this), but uncss isn't seeing it! Is this intentional?

**Comment by mikelambert** [comment] 2016-02-14 10:06
UnCSS intends to generate a new stylesheet, given an input stylesheet and html pages. Are you hoping that UnCSS would generate a new html page for you with all the style tags trimmed in-place?

It currently doesn't really have any mechanism for modifying/writing out html files.

Have you considered putting the CSS in a separate file, running it through UnCSS with the relevant HTML file referenced, and then your build process generates a "compiled" HTML file that includes the CSS file?

**Comment by RyanZim** [comment] 2016-05-24 13:54
@mikelambert Isn't this a dupe of #69?

**Comment by mikelambert** [comment] 2016-05-24 15:11
Yup, closing.

**Closed by mikelambert** 2016-05-24 15:11 UTC
